FROM golang:1.22-bookworm AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/redfish-mock ./cmd/redfish-mock
FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/redfish-mock /redfish-mock
USER nonroot:nonroot
EXPOSE 8000
ENTRYPOINT ["/redfish-mock"]
